# Generated by Django 4.0.4 on 2022-05-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=120)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=120)),
                ('mail', models.CharField(max_length=120)),
                ('location', models.TextField()),
                ('website', models.CharField(max_length=120)),
            ],
        ),
    ]
